name: Build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24.14.0"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: "10.32.1"

      - name: Verify env
        run: |
          node -v
          pnpm -v

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Zip dist
        run: |
          cd dist
          zip -r ../site.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site.zip
