name: Build

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      build_command:
        description: "选择构建脚本 (Choose build script)"
        required: true
        default: "build:client"
        type: choice
        options:
          - "build:client"
          - "build"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "10.32.1"

      - name: Verify env
        run: |
          node -v
          pnpm -v

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Run DSL tests
        run: pnpm run test:dsl

      - name: Build
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            pnpm run ${{ github.event.inputs.build_command }}
          else
            pnpm run build:client
          fi

      - name: Zip dist
        run: |
          cd dist
          zip -r ../site.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: site
          path: site.zip
